## Machine Learning Model
### Author: Kerry Effinger

In [2]:
import mysql.connector
import pandas as pd
import requests
import json
from datetime import date
import datetime
import time
import matplotlib.pyplot as plt
from pandas.plotting import table
import seaborn as sns

In [3]:
from yahoo_fin.stock_info import get_data
import yahoo_fin.stock_info as si
import yfinance as yf

In [45]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import numpy as np
from sklearn.linear_model import LinearRegression
import sklearn

In [5]:
df = pd.read_csv('CapstoneRegressionModel.csv')

In [6]:
df

Company       Location    Industry           Stage  \
0              Amazon        Seattle      Retail             IPO   
1         Pegasystems         Boston          HR             IPO   
2          Salesforce    SF Bay Area       Sales             IPO   
3               Vimeo  New York City    Consumer             IPO   
4              Amdocs      St. Louis     Support             IPO   
..                ...            ...         ...             ...   
388          Mediafly        Chicago       Sales  Private Equity   
389         Calibrate  New York City  Healthcare        Series B   
390      Drip Capital    SF Bay Area     Finance        Series C   
391        Astronomer     Cincinnati        Data        Series C   
392  Community Gaming  New York City      Crypto        Series A   

     Fed_int_rate  Number_laid_off  Percent  Money_raised_mm  BayAreaD  \
0             4.5             8000        2              108         0   
1             4.5              245        4                0         0   
2             4.5             8000       10               65         1   
3             4.5                0       11              450         0   
4             4.5              700        3                0         0   
..            ...              ...      ...              ...       ...   
388           5.0                0        0               59         0   
389           5.0                0       18              127         0   
390           5.0               75       20               85         1   
391           5.0              100        0              282         0   
392           5.0               17       17               18         0   

     SeattleD  ...  FinanceD  RetailD  ConsumerD  HRD  MarketingD  CryptoD  \
0           1  ...         0        1          0    0           0        0   
1           0  ...         0        0          0    1           0        0   
2           0  ...         0        0          0    0           0        0   
3           0  ...         0        0          1    0           0        0   
4           0  ...         0        0          0    0           0        0   
..        ...  ...       ...      ...        ...  ...         ...      ...   
388         0  ...         0        0          0    0           0        0   
389         0  ...         0        0          0    0           0        0   
390         0  ...         1        0          0    0           0        0   
391         0  ...         0        0          0    0           0        0   
392         0  ...         0        0          0    0           0        1   

     IPOD  AcquiredD  LowIntRateD  HighIntRateD  
0       1          0            1             0  
1       1          0            1             0  
2       1          0            1             0  
3       1          0            1             0  
4       1          0            1             0  
..    ...        ...          ...           ...  
388     0          0            0             1  
389     0          0            0             1  
390     0          0            0             1  
391     0          0            0             1  
392     0          0            0             1  

[393 rows x 23 columns]

## Linear regression Model for location Only:
using SF Bay Area, Seattle, Austin, and New York City

In [8]:
Locationarray = df[['BayAreaD','SeattleD','AustinD','NYCD']].to_numpy()
Locationarray
#df[['Courses', 'Duration']].to_numpy()

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [10]:
NLOarray = df['Number_laid_off'].to_numpy()
NLOarray

array([ 8000,   245,  8000,     0,   700,     0,    60,    75,    30,
         104,   200,     0,     0,    76,     0,    76,     0,     0,
         200,   388,    30,     0,     0,    40,    20,     0,     0,
           0,    43,   340,     0,     0,   950,   100,   100,   450,
          60,     0,     0,   640,     0,   123,   250,     0,    22,
          33,    55,    41,     0,   315,   104,    69,    40,   100,
           0,     0,   225,     0,     0,   270,     0,   120,     0,
           0,    46,     0,     0,     0,     0,    40,   140,     0,
       10000,    30,   284,     0,   155,    20,     0,   100,    44,
         100,   140,     0,   100,   450,   100,   300,    50,     0,
           0,     0,     0,   115,     0,   109,     0,    64,     0,
           0,    46,   275,   300,  1100,    22,    62,     0, 12000,
           0,     0,     0,     0,   100,   130,  1750,     0,     0,
          30,     0,    30,    47,     0,     0,     0,    50,    30,
         245,    40,

In [12]:
LocationModel = LinearRegression().fit(Locationarray, NLOarray)

r_sq = LocationModel.score(Locationarray, NLOarray)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {LocationModel.intercept_}")

print(f"coefficients: {LocationModel.coef_}")


coefficient of determination: 0.04087053558499143
intercept: 160.26451612903242
coefficients: [ 239.57758913 1002.9438172   669.4627566   -15.26451613]


## Linear Regression
> explantory variables: Location, Industry, Business Stage, and Federal Interest Rate

In [13]:
df.columns

Index(['Company', 'Location', 'Industry', 'Stage', 'Fed_int_rate',
       'Number_laid_off', 'Percent', 'Money_raised_mm', 'BayAreaD', 'SeattleD',
       'AustinD', 'NYCD', 'HealthcareD', 'FinanceD', 'RetailD', 'ConsumerD',
       'HRD', 'MarketingD', 'CryptoD', 'IPOD', 'AcquiredD', 'LowIntRateD',
       'HighIntRateD'],
      dtype='object')

In [28]:
NLO2.mean()

Number_laid_off    528.682927
dtype: float64

In [39]:
df['Number_laid_off'] = df['Number_laid_off'].replace(0, 529)
df

Company       Location    Industry           Stage  \
0              Amazon        Seattle      Retail             IPO   
1         Pegasystems         Boston          HR             IPO   
2          Salesforce    SF Bay Area       Sales             IPO   
3               Vimeo  New York City    Consumer             IPO   
4              Amdocs      St. Louis     Support             IPO   
..                ...            ...         ...             ...   
388          Mediafly        Chicago       Sales  Private Equity   
389         Calibrate  New York City  Healthcare        Series B   
390      Drip Capital    SF Bay Area     Finance        Series C   
391        Astronomer     Cincinnati        Data        Series C   
392  Community Gaming  New York City      Crypto        Series A   

     Fed_int_rate  Number_laid_off  Percent  Money_raised_mm  BayAreaD  \
0             4.5             8000        2              108         0   
1             4.5              245        4                0         0   
2             4.5             8000       10               65         1   
3             4.5              529       11              450         0   
4             4.5              700        3                0         0   
..            ...              ...      ...              ...       ...   
388           5.0              529        0               59         0   
389           5.0              529       18              127         0   
390           5.0               75       20               85         1   
391           5.0              100        0              282         0   
392           5.0               17       17               18         0   

     SeattleD  ...  FinanceD  RetailD  ConsumerD  HRD  MarketingD  CryptoD  \
0           1  ...         0        1          0    0           0        0   
1           0  ...         0        0          0    1           0        0   
2           0  ...         0        0          0    0           0        0   
3           0  ...         0        0          1    0           0        0   
4           0  ...         0        0          0    0           0        0   
..        ...  ...       ...      ...        ...  ...         ...      ...   
388         0  ...         0        0          0    0           0        0   
389         0  ...         0        0          0    0           0        0   
390         0  ...         1        0          0    0           0        0   
391         0  ...         0        0          0    0           0        0   
392         0  ...         0        0          0    0           0        1   

     IPOD  AcquiredD  LowIntRateD  HighIntRateD  
0       1          0            1             0  
1       1          0            1             0  
2       1          0            1             0  
3       1          0            1             0  
4       1          0            1             0  
..    ...        ...          ...           ...  
388     0          0            0             1  
389     0          0            0             1  
390     0          0            0             1  
391     0          0            0             1  
392     0          0            0             1  

[393 rows x 23 columns]

In [43]:
X = df[['BayAreaD','SeattleD','AustinD','NYCD','HealthcareD', 'FinanceD', 
        'RetailD', 'ConsumerD', 'HRD', 'MarketingD', 'CryptoD', 'IPOD', 
        'AcquiredD', 'LowIntRateD', 'HighIntRateD']].to_numpy()
y = df['Number_laid_off'].to_numpy()

In [41]:
y

array([ 8000,   245,  8000,   529,   700,   529,    60,    75,    30,
         104,   200,   529,   529,    76,   529,    76,   529,   529,
         200,   388,    30,   529,   529,    40,    20,   529,   529,
         529,    43,   340,   529,   529,   950,   100,   100,   450,
          60,   529,   529,   640,   529,   123,   250,   529,    22,
          33,    55,    41,   529,   315,   104,    69,    40,   100,
         529,   529,   225,   529,   529,   270,   529,   120,   529,
         529,    46,   529,   529,   529,   529,    40,   140,   529,
       10000,    30,   284,   529,   155,    20,   529,   100,    44,
         100,   140,   529,   100,   450,   100,   300,    50,   529,
         529,   529,   529,   115,   529,   109,   529,    64,   529,
         529,    46,   275,   300,  1100,    22,    62,   529, 12000,
         529,   529,   529,   529,   100,   130,  1750,   529,   529,
          30,   529,    30,    47,   529,   529,   529,    50,    30,
         245,    40,

### Splitting data 80/10/10:

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test_prime, y_train, y_test_prime = train_test_split(X, y, test_size=.20, random_state=42)

In [55]:
x_validate, x_test, y_validate, y_test = train_test_split(x_test_prime, y_test_prime, test_size=.50, random_state=42)

In [56]:
print(len(x_train), len(x_validate), len(x_test))

314 39 40


### Model:

In [58]:
LinModel = LinearRegression().fit(x_train, y_train)

r_sq = LinModel.score(x_train, y_train)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {LinModel.intercept_}")

print(f"coefficients: {LinModel.coef_}")


coefficient of determination: 0.12502107319883993
intercept: 231.56942592150222
coefficients: [  52.4435317   496.66136482  915.2439208  -251.32912806 -166.97618709
 -109.44390858  291.30456386 1131.67021746   67.67019568   76.2770506
   99.72509061  509.93868333 -159.40472661  -33.44940259   76.703552  ]


In [60]:
y_pred = LinModel.predict(x_test)

In [61]:
y_pred

array([ 760.50223835,  541.08251956,  360.71650961, 1114.07299014,
        632.06420067,  456.7295786 ,   88.67611475, 1078.46111273,
        308.27297792,  741.50810925,  231.56942592, 2002.3254104 ,
        297.84511394,  231.56942592,  870.22869154,  250.56355502,
         38.71529672,  -19.75970214,  250.56355502, 1204.72007147,
        708.05870666,  284.01295762,  284.01295762,  299.2396216 ,
        198.12002333,  148.86825131,  440.17281517, 1314.87302606,
        141.11964644,  265.79021901,  489.42458719,   83.58736793,
        574.53192216,  250.56355502, 1161.9597568 , 1529.47403793,
       1238.16947407,  198.12002333,  274.39707392, 1839.72892411])

### Assess Performance of Model:
> Evaluating model with mean squared error (MSE), root mean squared error (RMSE), mean absolute error (MAE), and R-squared (R2) score.

In [64]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [65]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [67]:
print(f"Metrics for 80/10/10 split are:\n MSE:{mse},\n RMSE:{rmse},\n mae:{mae},\nr2:{r2}")

Metrics for 80/10/10 split are:
 MSE:2248525.4495628024,
 RMSE:1499.50840263161,
 mae:591.0690416716808,
r2:0.02382555471573533


In [68]:
from sklearn import metrics